In [5]:
import numpy as np

In [98]:
# Define Activation Functions and Their Derivatives #
##################################################################################
# relu activation function
def relu(z):
    return np.maximum(0, z)
##################################################################################
# relu derivative 
def reluDerivative(z):
    z[z <= 0] = 0
    z[z > 0] = 1
    return z
##################################################################################
# sigmoid activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
##################################################################################
# sigmoid derivative
def sigmoidDerivative(z):
    return sigmoid(z) * (1 - sigmoid(z))
##################################################################################

In [112]:
# Define Neural Network Architecture #
##################################################################################
# neural network architecture
class NeuralNetwork:
    # neural network with one hidden layer made of s2 nodes 
    def __init__(self, x_dim, s2):
        self.theta1 = np.random.rand(s2, x_dim + 1)
        self.theta2 = np.random.rand(1, s2 + 1)
    # perform feed forward and calculate loss    
    def feedForward(self, x, y, bias=1):
        self.x = np.insert(x, 0, bias)
        self.y = y
        self.h1_in = np.dot(self.theta1, self.x)
        #self.h1_out = np.insert(relu(self.h1_in), 0, bias)
        #self.o_in = np.dot(self.theta2, self.h1_out)
        #self.o_out = sigmoid(self.o_in) 
        #self.loss = 0.5 * np.square(self.y - self.o_out)
    # perform backpropagation and update weights 
    def backPropagation(self):
        self.delta_theta2 = (self.o_out - self.y) * sigmoidDerivative(self.o_in) * self.h1_out
        #delta_theta1 = np.dot((self.o_out - self.y) * sigmoidDerivative(self.o_in) * self.theta2 * reluDerivative(self.h1_in), self.x)
        
        #self.theta2 -= delta_theta2
        #self.theta1 -= delta_theta1
##################################################################################

In [127]:
NN1 = NeuralNetwork(2, 2)
NN1.feedForward(x[0], y[0])
NN1.theta1, NN1.theta2.shape, NN1.h1_in.shape

(array([[0.84562821, 0.88307434, 0.40002976],
        [0.88772068, 0.47663586, 0.48354877]]), (1, 3), (2,))

In [126]:
NN1.feedForward(x[0], y[0])
NN1.x.shape, NN1.y, NN1.h1_in

((3,), 0, array([0.78568191, 0.1552132 ]))

In [119]:
# set labeled inputs
x = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([0, 1, 1, 0])
y.shape

(4,)

In [90]:
NN1 = NeuralNetwork(2, 2)

In [91]:
NN1.feedForward(x[1], y[1])

In [92]:
NN1.loss

array([0.01040457])

In [93]:
NN1.backPropagation()

In [94]:
NN1.delta_theta2

array([-0.0958924 , -0.14757374])